#!/bin/sh
# /etc/init.d/ptp4linit

### BEGIN INIT INFO
# Provides:          ptp4linit
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts ptp4l at boot
# Description:       Enables Precision Time Protocol (PTP) using ptp4l.
### END INIT INFO

case "$1" in
  start)
    echo "Starting ptp4l"
    /home/lvuser/deploy/timing/ptp4l -i eth0 -S
    ;;
  stop)
    echo "Stopping ptp4l"
    # Add command to stop ptp4l if applicable
    ;;
  *)
    echo "Usage: /etc/init.d/ptp4linit {start|stop}"
    exit 1
    ;;
esac

exit 0